server:
  port: 8010
  tomcat:
    accept-count: 500
    max-threads: 100
    min-spare-threads: 50
    max-connections: 5000

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
swagger2:
  enable: true

druid:
  spring:
    monitor:
      enable: false
      locations: com.sample.*

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: ENC(onvT1m5Xiwv7JTqBiMYZ+gW4LxwShCTPVk06Iuq5MhWZGhYGuEYqdg8Q1I/LfqZ5Xc7bw1XaYp9gD3Kuug9JvG5WtfmKAeSCIpXghnnG9dzhopbQbGPETsp6XqzGoTIE8ELrlIXDUbIFOAwW24Lj7lAXUd0xF70AmxX1TCqE8jL6S0cYSHXbq+3y7BykEf30)
      username: ENC(uVs7DP260FXOKYBacQjLo7Fonyyiq2qwnSjOGt9Q2weCl3ceVf6c6VAAQ6WkTsUt)
      password: ENC(IkxnRsO4O+J/8pOvHoL7/9sSyvhq3Zv9AYObJx9ldt636qyRiBTGrwndtSISEY4F)
      initial-size: 10
      minIdle: 50
      maxActive: 500
      maxWait: 60000
      fail-fast: true
      Keep-alive: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      filters: stat,wall,slf4j
      maxPoolPreparedStatementPerConnectionSize: 100
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        #访问路径为/druid时，跳转到StatViewServlet  http://127.0.0.1:8080/druid
        url-pattern: "/druid/*"
        reset-enable: falseEcException
        login-username: ENC(1j3TT4M6aHscVzKpeHWX5KNKRU7ui1jesPGY52W2FEl9WunVIBiVizoeQv4ocWxd)
        login-password: ENC(Jm9wTCpswKDpVkuiT0JmwMiz7H4bqiOLnEK1Hs49QPrB+RJ4Y8pUh2ON4FPOSjNV)
  cloud:
    nacos:
      discovery:
        server-addr: ENC(cNeNQ2aZrxpTNiCi3S6Q91aZd32na9V8jLizHKlnhHlTwXJ4gq9WAMYJgK+9gRuzuZpRqnbYcLowywVvyXADDg==)
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    ec.*: debug

