custom-config:
  server-addr: ENC(xtrTzLo6BCn9c+RVe7sbhOE+hiLTYbeqg6/IVTY72RezzASal7tmVksSsdN6rLoja/P5M8Svgfa3AkNnO+cToQ==)
  group: EC_COUPON
  file-extension: yaml
  datasource: datasource.yaml
  server: server.yaml
  other: others.yaml
  ec-group: EC_GROUP
  log: logging.yaml

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

server:
  port: 8020
  tomcat:
    accept-count: 500
    max-threads: 100
    min-spare-threads: 50
    max-connections: 5000

swagger2:
  enable: true

druid:
  spring:
    monitor:
      enable: false
      locations: com.sample.*

spring:
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 45MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    ec.*: debug
