language: java

git:
  depth: 2

services:
  - docker

jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - node_modules

install:
  - nvm install stable
  - nvm use stable
  - npm install

branches:
  only:
    - develop
    - project-ec

jobs:
  include:
    ############################################################## backend #############################################################################################
    - stage: build-$project_name-ec-admin
      script:
        - export module_name=ec-admin
        # build project
        - cd $project_home/backend/$project_name
        - travis_wait $travis_wait ./gradlew clean build -x test --console=plain
        # push image
        - image_tag=project-$module_name:`date +%Y%m%d`.${TRAVIS_COMMIT:0:7}
        - cd $project_home/backend/$project_name/$module_name
        - docker build -f Dockerfile --build-arg MODULE_NAME=$module_name -t $image_tag .
        - sudo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD $DOCKER_REPO
        - sudo docker tag $image_tag $DOCKER_REPO/alice52/$image_tag
        - travis_wait $travis_wait sudo docker push $DOCKER_REPO/alice52/$image_tag

    ############################################################## backend #############################################################################################
    - stage: build-$project_name-ec-admin-front
      script:
        - export module_name=ec-admin
        # build project
        - cd $project_home/frontend/$module_name
        - travis_wait $travis_wait nmp run build
        # push image
        - image_tag=project-front-$module_name:`date +%Y%m%d`.${TRAVIS_COMMIT:0:7}
        - cd $project_home/frontend/$module_name
        - docker build -f Dockerfile -t $image_tag .
        - sudo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD $DOCKER_REPO
        - sudo docker tag $image_tag $DOCKER_REPO/alice52/$image_tag
        - travis_wait $travis_wait sudo docker push $DOCKER_REPO/alice52/$image_tag
notifications:
  email:
    recipients:
      - zzhang_xz@163.com
    on_success: always # default: change
    on_failure: always # default: always

env:
  travis_wait: 50
  project_name: project-ec
  project_home: $PWD
  commit_id: 000
  image_tag: 000
