server:
  port: 8050
  tomcat:
    accept-count: 500
    max-threads: 100
    min-spare-threads: 50
    max-connections: 5000

custom-config:
  server-addr: ENC(xtrTzLo6BCn9c+RVe7sbhOE+hiLTYbeqg6/IVTY72RezzASal7tmVksSsdN6rLoja/P5M8Svgfa3AkNnO+cToQ==)
  group: EC_WARE
  file-extension: yaml
  datasource: datasource.yaml
  server: server.yaml
  other: others.yaml
  ec-group: EC_GROUP
  log: logging.yaml

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
swagger2:
  enable: true

spring:
  devtools:
    livereload:
      port: 35731
  # oss
  cloud:
    alicloud:
      access-key: ENC(Kf42+pHi8/IU/QWZlOm8UpTTLIMxHWRBWkYENv7a1hO93AkB/rb0G9juNLPXSAfpzYVkX4DGFvUKC1qLooR9Yw==)
      secret-key: ENC(zu07F3mfQ5SeGQR2YG3q7OWoRMoJPE73C5DWwqxV8LWyz8MOGpz0viKcdadOBeS/Gp54+V0LWWC8jjWIoVTbnA==)
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket-name: ENC(xJHHZLCs0MUV7V9RH7Mc4Cn8foAUYQHk4pQ5tdVuU1EEqRF2sZjk57O61kYYTy04)
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

logging:
  level:
    ec.*: debug
