custom-config:
    namespace: 582f8a8e-70fd-4ccd-b350-13bdfb429d49

spring:
    profiles:
        include: common
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driverClassName: com.mysql.cj.jdbc.Driver
            url: ENC(Mvnjrztf/6fuXCnGcsSIMUsH8jp5uGtzEvjBbzo8zN18o5Qh8LRq8Qa6mUHPf+bgsx5S/GYYG2m7GCPfSNJBt1ZcnPFD4nulFzOTcscjCV1IpVOS3yW0L5VF6nWqoDslCcjQaXnX6ODGymi0ujUpXre+0bqUpfW++USfMQIJ1hq5S67gWQO2ANzyAhuAsJEt)
            username: ENC(uVs7DP260FXOKYBacQjLo7Fonyyiq2qwnSjOGt9Q2weCl3ceVf6c6VAAQ6WkTsUt)
            password: ENC(IkxnRsO4O+J/8pOvHoL7/9sSyvhq3Zv9AYObJx9ldt636qyRiBTGrwndtSISEY4F)
            initial-size: 10
            minIdle: 50
            maxActive: 500
            maxWait: 60000
            fail-fast: true
            Keep-alive: true
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: false
            filters: stat,wall,slf4j
            maxPoolPreparedStatementPerConnectionSize: 100
            useGlobalDataSourceStat: true
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
            web-stat-filter:
                enabled: true
                url-pattern: /*
                exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
            stat-view-servlet:
                enabled: true
                #访问路径为/druid时，跳转到StatViewServlet  http://127.0.0.1:8080/druid
                url-pattern: "/druid/*"
                reset-enable: falseEcException
                login-username: ENC(1j3TT4M6aHscVzKpeHWX5KNKRU7ui1jesPGY52W2FEl9WunVIBiVizoeQv4ocWxd)
                login-password: ENC(Jm9wTCpswKDpVkuiT0JmwMiz7H4bqiOLnEK1Hs49QPrB+RJ4Y8pUh2ON4FPOSjNV)
