version: '2.4'
services:
  ec-admin:
    image: registry.cn-shanghai.aliyuncs.com/alice52/project-ec-admin:20201004.63d62d8
    restart: 'on-failure:3'
    container_name: project-ec-admin
    ports:
      - 9001:9001
    volumes:
      # this is for nginx look up
      - /root/nginx/www/project-ec/ec-admin:/log
    environment:
      TZ: Asia/Shanghai


  ec-admin-front:
    image: registry.cn-shanghai.aliyuncs.com/alice52/project-front-ec-admin:20201004.63d62d8
    restart: 'on-failure:3'
    container_name: project-ec-admin-front
    ports:
      - 82:80
    volumes:
      # - /root/nginx/www:/usr/share/nginx/html
      - /root/ec/ec-admin-front/logs:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai

  nginx:
    image: registry.cn-shanghai.aliyuncs.com/alice52/dev-nginx:20200929.b7b0fc7
    restart: always
    container_name: project-ec-nginx
    ports:
      - 81:80
    volumes:
      - /root/ec/nginx/conf/nginx.conf/nginx.conf:/etc/nginx/nginx.conf
      - /root/ec/nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /root/ec/nginx/www:/usr/share/nginx/html
      - /root/ec/nginx/logs:/var/log/nginx
    environment:
      TZ: Asia/Shanghai
