version: '2.4'
services:
  # notice handle legacy data, grant.
  mysql-master:
    image: registry.cn-shanghai.aliyuncs.com/alice52/dev-mysql-master-5.7:20201221.1161b86
    restart: 'on-failure:3'
    container_name: dev-mysql-master
    ports:
      - 3306:3306
    volumes:
      - /root/mysql/logs:/var/log/mysql
      - /root/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Shanghai

  # hanlde legacy data, connection, slave, read-only.
  mysql-slave:
    image: registry.cn-shanghai.aliyuncs.com/alice52/dev-mysql-slave-5.7:20201221.1161b86
    restart: 'on-failure:3'
    container_name: dev-mysql-slave
    ports:
      - 3306:3306
    volumes:
      #- /root/mysql/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - /root/mysql/master/logs:/var/log/mysql
      - /root/mysql/master/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Shanghai

  redis:
    image: registry.cn-shanghai.aliyuncs.com/alice52/dev-standalone-redis:20200930.4e34876
    restart: 'on-failure:3'
    container_name: dev-redis-standalone
    ports:
      - 6379:6379
    volumes:
      - /root/redis/standalone/data:/data
    environment:
      TZ: Asia/Shanghai
