version: '2.4'
services:
  nacos:
    image: registry.cn-shanghai.aliyuncs.com/alice52/dev-nacos:20201031.0c79aa9
    container_name: dev-nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - /root/nacos/standalone/logs/:/home/nacos/logs
    ports:
      - '8848:8848'
