server:
  port: 8008

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

swagger2:
  enable: true

spring:
  application:
    name: project-seckill
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false