server:
  port: 8008

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

swagger2:
  enable: true

druid:
  spring:
    monitor:
      enable: true
      locations: cn.edu.ntu.seckill.repository.*

spring:
  application:
    name: project-seckill
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    # driver-class-name, username, password, url should be in druid, otherwise will lead to SQL monitor not work
    # check datasource in UI first, then check `filter class name`
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: ENC(G07wPxuyb9kJOnY3JjNFCvUhVlMQihy/APHD0HnhHzg2qT/na3j2k/kViG7H4hVV)
      password: ENC(+hH8DdzTl3EIcR7kB7ZVGK7/WQR4GquK6LIo7apn7HXT3yD4T1QrAAUORMxqnORZ)
      url: ENC(DBdwDUQtm1qbuWx7KCZ2OKFxSBtCe+xtGbMiUEOu91YC9HSXYa3auy/vjGFl1/IhlEf+DzNd5bVAlmzwr8S8XW/I4+WTaN8J41QbnpwDRB0wJTmReVw7+j0VNSFRB9Hsv4yLvvmGYHi6rEjwKADtjIHQhkkhdqrOc6Ks2Sh/cbI=)
      initial-size: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      # Configure monitoring statistics interception filters.
      # If removed, the monitoring interface sql cannot collect statistics.
      # Wall is used for the firewall
      filters: stat,wall,slf4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      # aop-patterns: com.web.springbootdruid.service.*
      # 进行监控配置
      web-stat-filter:
        #是否启用StatFilter默认值true
        enabled: true
        #添加过滤规则
        url-pattern: /*
        #忽略过滤的格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        #是否启用StatViewServlet默认值true
        enabled: true
        #访问路径为/druid时，跳转到StatViewServlet  http://127.0.0.1:8080/druid
        url-pattern: "/druid/*"
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台，默认为root
        login-username: ENC(1j3TT4M6aHscVzKpeHWX5KNKRU7ui1jesPGY52W2FEl9WunVIBiVizoeQv4ocWxd)
        login-password: ENC(Jm9wTCpswKDpVkuiT0JmwMiz7H4bqiOLnEK1Hs49QPrB+RJ4Y8pUh2ON4FPOSjNV)
        #IP白名单
        allow:
        #&emsp;IP黑名单（共同存在时，deny优先于allow）
        # deny: 127.0.0.1

      # # slow query
      # filter:
      #   stat:
      #     slow-sql-millis: 200
      #     log-slow-sql: true
      #   slf4j:
      #     data-source-log-enabled: true
      #     statement-executable-sql-log-enable: true
  mail:
    protocol: smtp
    host: ENC(KwgyFVRJzE76uUF+B2EOyjJgijQDrxhRWzrUBa6eUfmduClTbtpaCVxXRWWctYSi)
    port: ENC(nvvb0wOLlW+Kl+2CLMay0AyhVmWzXr5Ma2Tn4hTWSyMb95lPCjaIXpHm2Oms/9rB)
    default-encoding: ENC(qB9K/XFkIcJGH80lNU2gJ2DVOLsFI6uuyui9MoAQA+ZI1WCLjAOjNfU7rrp3h3qo)
    username: ENC(XtxDqyspABu9dQ0xSZ0zRV7MfVfk/7tN1rE/wkjko5vcjA0vgqmcE10FxRRYlribavOUtBGNy2PDPHWtIrrFUg==)
    password: ENC(cVfVnGq4tQ6J3+FtW0TejImmx2ESWomD/tuGN5bJqMGM8v+Of/onqraHBd9xhH0J)
    properties:
      mail:
        smtp:
          # this is also need by qq email server
          ssl:
            enable: true
            required: true
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 10000
          connectiontimeout: 10000
          writetimeout: 10000

  redis:
    host: ENC(6hY7MaESdo1jx/6ZHRAMcHM701ZVhEyLnFQpizADsXyOEUjgL8CNhqcTJJQOk9CK)
    port: ENC(eGEvmyM63hvc7Vj3XoQArH7v0Uf2vsQTJcnZptv+ykd9zfrJ9GkCe03HF2r1z6KS)
    password: ENC(1oOxsSuSGMpyyG2EtWiIS9dGTLSwjE5U6gsqwG8+4ynRf+5Rwavd9zQ7juioMMYh)
    database: 10
    # this is million second
    timeout: 10000
    jedis:
      pool:
        max-active: 50
        min-idle: 20

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.ntu.seckill.model

management:
  endpoints:
    web:
      exposure:
        include: 'loggers'