server:
  port: 8060
  tomcat:
    accept-count: 500
    max-threads: 100
    min-spare-threads: 50
    max-connections: 5000

spring:
  cloud:
    gateway:
      routes:
        - id: thirdparty_route
          uri: lb://EC-THIRDPARTY-SERVICE
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: product_route
          uri: lb://EC-PRODUCT-SERVICE
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://EC-ADMIN-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/ec-admin/$\{segment}
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  level:
    ec.*: debug
    root: info

