server:
  port: 8080

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ENC(onvT1m5Xiwv7JTqBiMYZ+gW4LxwShCTPVk06Iuq5MhWZGhYGuEYqdg8Q1I/LfqZ5Xc7bw1XaYp9gD3Kuug9JvG5WtfmKAeSCIpXghnnG9dzhopbQbGPETsp6XqzGoTIE8ELrlIXDUbIFOAwW24Lj7lAXUd0xF70AmxX1TCqE8jL6S0cYSHXbq+3y7BykEf30)
    username: ENC(uVs7DP260FXOKYBacQjLo7Fonyyiq2qwnSjOGt9Q2weCl3ceVf6c6VAAQ6WkTsUt)
    password: ENC(IkxnRsO4O+J/8pOvHoL7/9sSyvhq3Zv9AYObJx9ldt636qyRiBTGrwndtSISEY4F)
    #oracle配置
    #    driverClassName: oracle.jdbc.OracleDriver
    #    url: jdbc:oracle:thin:@47.100.206.162:1521:xe
    #    username: renren
    #    password: 123456
    #SQLServer配置
    #    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=renren_fast
    #    username: sa
    #    password: 123456
    #PostgreSQL配置
  #    driverClassName: org.postgresql.Driver
  #    url: jdbc:postgresql://192.168.10.10:5432/renren_fast
  #    username: postgres
  #    password: 123456

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/

#mongodb:
#  host: localhost
#  port: 27017
#  auth: false #是否使用密码验证
#  username: tincery
#  password: renren
#  source: 123456
#  database: test

mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml

pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#指定数据库, 可选值有【mysql、oracle、sqlserver、postgresql、mongodb】
renren:
  database: mysql

