name: Build Image Ec-Backend

on:
  push:
    branches:
      - project-ec
    paths:
      - 'backend/**'
      - '.github/**'

jobs:
  main:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[image]')"
    env: # define constant
      PROJECT_NAME: project-ec
      IMAGE_PREFIX: project

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          # architecture: x64

      - name: Cache Gradle Packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build With Gradle
        run: |
          cd backend/project-ec
          ./gradlew clean build -x test --console=plain

      - name: Export Global Var
        # define global var, then put to GITHUB_ENV
        run: |
          echo "ALI_DOCKER_REGISTRY=${{ secrets.ALI_DOCKER_HUB_REGISTRY }}" >> $GITHUB_ENV
          echo "ALI_DOCKER_USERNAME=${{ secrets.ALI_DOCKER_REGISTRY_USERNAME }}" >> $GITHUB_ENV
          echo "ALI_DOCKER_PASSWORD=${{ secrets.ALI_DOCKER_REGISTRY_PASSWORD }}" >> $GITHUB_ENV
          echo "JASYPT_ENCRYPTOR_PASSWORD=${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}" >> $GITHUB_ENV
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> $GITHUB_ENV
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> $GITHUB_ENV
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> $GITHUB_ENV
          echo "PROJECT_HOME=$PWD" >> $GITHUB_ENV
          echo "TAG=`echo \`date +%Y%m%d\`.${GITHUB_SHA} | cut -c1-16`" >> $GITHUB_ENV

      - name: Push Ec-Admin
        run: |
          MODULE_NAME=ec-admin
          cd $PROJECT_HOME/backend/$PROJECT_NAME/$MODULE_NAME/
          image=$IMAGE_PREFIX-$MODULE_NAME:${TAG}
          docker build -f Dockerfile --build-arg MODULE_NAME=$MODULE_NAME --build-arg JASYPT_ENCRYPTOR_PASSWORD=$JASYPT_ENCRYPTOR_PASSWORD --build-arg REDIS_PASSWORD=$REDIS_PASSWORD --build-arg MONGO_PASSWORD=$MONGO_PASSWORD -t ${image} .
          docker login --username=$ALI_DOCKER_USERNAME --password=$ALI_DOCKER_PASSWORD $ALI_DOCKER_REGISTRY
          docker tag $image $ALI_DOCKER_REGISTRY/alice52/$image
          docker push $ALI_DOCKER_REGISTRY/alice52/$image
          echo "image:" ${image}

      - name: Push Ec-Product
        run: |
          MODULE_NAME=ec-product
          cd $PROJECT_HOME/backend/$PROJECT_NAME/$MODULE_NAME/
          image=$IMAGE_PREFIX-$MODULE_NAME:${TAG}
          docker build -f Dockerfile --build-arg MODULE_NAME=$MODULE_NAME --build-arg JASYPT_ENCRYPTOR_PASSWORD=$JASYPT_ENCRYPTOR_PASSWORD --build-arg REDIS_PASSWORD=$REDIS_PASSWORD --build-arg MONGO_PASSWORD=$MONGO_PASSWORD -t ${image} .
          docker login --username=$ALI_DOCKER_USERNAME --password=$ALI_DOCKER_PASSWORD $ALI_DOCKER_REGISTRY
          docker tag $image $ALI_DOCKER_REGISTRY/alice52/$image
          docker push $ALI_DOCKER_REGISTRY/alice52/$image
          echo "image:" ${image}

      - name: Push Ec-Coupon
        run: |
          MODULE_NAME=ec-coupon
          cd $PROJECT_HOME/backend/$PROJECT_NAME/$MODULE_NAME/
          image=$IMAGE_PREFIX-$MODULE_NAME:${TAG}
          docker build -f Dockerfile --build-arg MODULE_NAME=$MODULE_NAME --build-arg JASYPT_ENCRYPTOR_PASSWORD=$JASYPT_ENCRYPTOR_PASSWORD --build-arg REDIS_PASSWORD=$REDIS_PASSWORD --build-arg MONGO_PASSWORD=$MONGO_PASSWORD -t ${image} .
          docker login --username=$ALI_DOCKER_USERNAME --password=$ALI_DOCKER_PASSWORD $ALI_DOCKER_REGISTRY
          docker tag $image $ALI_DOCKER_REGISTRY/alice52/$image
          docker push $ALI_DOCKER_REGISTRY/alice52/$image
          echo "image:" ${image}

      - name: Push Ec-Order
        run: |
          MODULE_NAME=ec-order
          cd $PROJECT_HOME/backend/$PROJECT_NAME/$MODULE_NAME/
          image=$IMAGE_PREFIX-$MODULE_NAME:${TAG}
          docker build -f Dockerfile --build-arg MODULE_NAME=$MODULE_NAME --build-arg JASYPT_ENCRYPTOR_PASSWORD=$JASYPT_ENCRYPTOR_PASSWORD --build-arg REDIS_PASSWORD=$REDIS_PASSWORD --build-arg MONGO_PASSWORD=$MONGO_PASSWORD -t ${image} .
          docker login --username=$ALI_DOCKER_USERNAME --password=$ALI_DOCKER_PASSWORD $ALI_DOCKER_REGISTRY
          docker tag $image $ALI_DOCKER_REGISTRY/alice52/$image
          docker push $ALI_DOCKER_REGISTRY/alice52/$image
          echo "image:" ${image}

      - name: Push Ec-Ware
        run: |
          MODULE_NAME=ec-ware
          cd $PROJECT_HOME/backend/$PROJECT_NAME/$MODULE_NAME/
          image=$IMAGE_PREFIX-$MODULE_NAME:${TAG}
          docker build -f Dockerfile --build-arg MODULE_NAME=$MODULE_NAME --build-arg JASYPT_ENCRYPTOR_PASSWORD=$JASYPT_ENCRYPTOR_PASSWORD --build-arg REDIS_PASSWORD=$REDIS_PASSWORD --build-arg MONGO_PASSWORD=$MONGO_PASSWORD -t ${image} .
          docker login --username=$ALI_DOCKER_USERNAME --password=$ALI_DOCKER_PASSWORD $ALI_DOCKER_REGISTRY
          docker tag $image $ALI_DOCKER_REGISTRY/alice52/$image
          docker push $ALI_DOCKER_REGISTRY/alice52/$image
          echo "image:" ${image}

      - name: Push Ec-Gateway
        run: |
          MODULE_NAME=ec-gateway
          cd $PROJECT_HOME/backend/$PROJECT_NAME/$MODULE_NAME/
          image=$IMAGE_PREFIX-$MODULE_NAME:${TAG}
          docker build -f Dockerfile --build-arg MODULE_NAME=$MODULE_NAME --build-arg JASYPT_ENCRYPTOR_PASSWORD=$JASYPT_ENCRYPTOR_PASSWORD --build-arg REDIS_PASSWORD=$REDIS_PASSWORD --build-arg MONGO_PASSWORD=$MONGO_PASSWORD -t ${image} .
          docker login --username=$ALI_DOCKER_USERNAME --password=$ALI_DOCKER_PASSWORD $ALI_DOCKER_REGISTRY
          docker tag $image $ALI_DOCKER_REGISTRY/alice52/$image
          docker push $ALI_DOCKER_REGISTRY/alice52/$image
          echo "image:" ${image}

      - name: Push Ec-Thirdparty
        run: |
          MODULE_NAME=ec-thirdparty
          cd $PROJECT_HOME/backend/$PROJECT_NAME/$MODULE_NAME/
          image=$IMAGE_PREFIX-$MODULE_NAME:${TAG}
          docker build -f Dockerfile --build-arg MODULE_NAME=$MODULE_NAME --build-arg JASYPT_ENCRYPTOR_PASSWORD=$JASYPT_ENCRYPTOR_PASSWORD --build-arg REDIS_PASSWORD=$REDIS_PASSWORD --build-arg MONGO_PASSWORD=$MONGO_PASSWORD -t ${image} .
          docker login --username=$ALI_DOCKER_USERNAME --password=$ALI_DOCKER_PASSWORD $ALI_DOCKER_REGISTRY
          docker tag $image $ALI_DOCKER_REGISTRY/alice52/$image
          docker push $ALI_DOCKER_REGISTRY/alice52/$image
          echo "image:" ${image}
