name: Java CI Project EC

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          # architecture: x64

      - name: Cache Gradle Packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build With Gradle
        run: |
          cd backend/project-ec
          ./gradlew clean build -x test --console=plain

      - name: Upload Gradle common Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ec-common-1.0-SNAPSHOT.jar
          path: backend/project-ec/ec-common/build/libs

      - name: Upload Gradle coupon Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ec-coupon-1.0-SNAPSHOT.jar
          path: backend/project-ec/ec-coupon/build/libs

      - name: Upload Gradle gateway Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ec-gateway-1.0-SNAPSHOT.jar
          path: backend/project-ec/ec-gateway/build/libs

      - name: Upload Gradle member Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ec-member-1.0-SNAPSHOT.jar
          path: backend/project-ec/ec-member/build/libs

      - name: Upload Gradle order Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ec-order-1.0-SNAPSHOT.jar
          path: backend/project-ec/ec-order/build/libs

      - name: Upload Gradle product Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ec-product-1.0-SNAPSHOT.jar
          path: backend/project-ec/ec-product/build/libs

      - name: Upload Gradle ware Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ec-ware-1.0-SNAPSHOT.jar
          path: backend/project-ec/ec-ware/build/libs

      - name: Upload Gradle thirdparty Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ec-thirdparty-1.0-SNAPSHOT.jar
          path: backend/project-ec/ec-thirdparty/build/libs
